### ISSUE TITLE
bluc_p11, ff, win: Erro no JSON de listCerts quando há mais de 1 certificado

### ISSUE THREAD

**Issue by crivano** [bluecrystalsign/bluecrystal-signer#3]
Está ocorrendo um erro novo na applet P11. Quando temos 2 certificados instalados, a função listCerts está voltando um JSON inválido. 
 
Tem dois objetos [{}{}], mas não tem uma vírgula entre eles.

**Comment by bluecrystalsign** [comment]
Funciona em outro navegador?

**Comment by crivano** [comment]
Só consegui rodar em FF até agora. O Chrome bloqueia applets e o IE ainda não sei. Vou verificar.

**Comment by crivano** [comment]
a nova versão de bluc_p11.jar não resolveu este problema. Continua sem a vírgula.

**Comment by bluecrystalsign** [comment]
vc pode 'liberar' o applet no chrome
http://www.adminarsenal.com/admin-arsenal-blog/powershell-enabling-disabling-google-chrome-plugins-using-the-registry

**Comment by bluecrystalsign** [comment]
Certifique-se de que o FF ta carregando essa ultima versao..
No console do Java ele escreve o json

**Comment by bluecrystalsign** [comment]
e o json sai sem a virgula?

**Comment by crivano** [comment]
Consegui habilitar o java no chrome.

**Comment by crivano** [comment]
Corrigido na última versão.
